//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticSemenov.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudent
    {
        public int IdExamStudent { get; set; }
        public Nullable<int> IdExam { get; set; }
        public int RegNumber { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
