//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticSemenov.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseForPracticEntities1 : DbContext
    {
        public BaseForPracticEntities1()
            : base("name=BaseForPracticEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Cafedra> Cafedra { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EnginerSpeciality> EnginerSpeciality { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<ExamStudent> ExamStudent { get; set; }
        public virtual DbSet<Facultet> Facultet { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Title> Title { get; set; }
    }
}
